services:
  - type: web
    name: fake-news-detector # You can name this whatever you like
    env: python
    runtime: python # This will use the version from runtime.txt
    plan: free # Use the free tier (be aware of memory limits!)
    
    buildCommand: ./build.sh
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT app:app

    # This section syncs your files
    autoDeploy: true 
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13 # Match your runtime.txt